### ISSUE TITLE
XP12.1.3b1 - Avitab crashes x-plane when pening pdf charts

### ISSUE THREAD

**Issue by domrnet** [fpw/avitab#213] opened 2024-11-18 09:45 UTC
Hi

With the new XP12.1.3b1 I am able to openAvitab fine. Map works fine but if I open a PDF chart or document it crashes Xplane. This also happens with chartfox charts. 

The x-plane log just gives an arts control message but if I run form the command line I see the following as soon as I open a chart ...

> [48839:48839:20241118,100816.102365:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.127665:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.127912:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.128083:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.133733:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.133851:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.133964:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.134180:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.135016:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.135923:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136023:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136114:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136226:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136318:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136393:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136500:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136683:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136791:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136889:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.136986:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137098:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137214:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137309:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137486:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137617:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137718:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137845:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.137939:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.138049:ERROR elf_dynamic_array_reader.h:64] tag not found
> [48839:48839:20241118,100816.140098:ERROR process_memory_range.cc:75] read out of range
> [48839:48839:20241118,100816.140181:ERROR process_memory_range.cc:75] read out of range
> [48839:48839:20241118,100816.163902:WARNING thread_snapshot_linux.cc:112] Unknown scheduling policy 1073741826
> [48839:48839:20241118,100816.170778:WARNING thread_snapshot_linux.cc:112] Unknown scheduling policy 1073741826
> [48839:48839:20241118,100816.172378:WARNING thread_snapshot_linux.cc:112] Unknown scheduling policy 1073741826
> [48839:48839:20241118,100816.173433:WARNING thread_snapshot_linux.cc:112] Unknown scheduling policy 1073741826
> [48839:48839:20241118,100816.197262:ERROR process_memory_range.cc:75] read out of range
> [48839:48839:20241118,100816.197287:ERROR process_memory_range.cc:75] read out of range
> [48839:48839:20241118,100816.197471:ERROR process_memory_range.cc:75] read out of range
> [48839:48839:20241118,100816.197487:ERROR process_memory_range.cc:75] read out of range
> MicroProfile: Web server started on 127.0.0.1:1339
> MicroProfile: Web server started on 192.168.0.45:1339
> Picking device: NVIDIA GeForce RTX 3060
> Segmentation fault (core dumped)

System specs:

Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4790 CPU @ 3.60GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2

 I have run a mem test and that was ok (I see the error mentions memory so thought best to eliminate that)

**Comment by mjh65** [comment] 2024-11-20 11:29
Thought I would just try a quick test to see if I could reproduce this, and I could not. My system is an AMD Windows 11, so not identical.
I'm wondering why the new X-Plane beta might result in the changed behaviour, since (AFAIK) opening PDF files doesn't use any of the X-Plane APIs. Displaying the rasterized PDF pages does use the graphics API, but this is also true for maps. I wonder do other document types (eg PNG, JPG) open and display correctly? Is it only PDF files that cause a crash?
This doesn't feel like an Avitab issue, but equally there also aren't any other obvious suspects.
Very strange!

**Comment by sparker256** [comment] 2024-11-21 03:48
I found the same thing with my Ubuntu 24.04 install. I sent the crash reported to LR. I used the readme.pdf in the charts folder and then opened it with the Ubuntu Document and it opened fine.

**Comment by domrnet** [comment] 2024-11-21 08:21
I have even upgraded to my setup to Kubuntu 24.10 just to see if that had any impact but no.  
JPG - Crash
PNG - Crash
PDF- Crash
Same errors as I had previously posted however I missed this line before, not sure if it is relevant..

Warning: terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so. Skipping this driver.


So whatever has happened with the new beta has introduced something. Avitab is working fine on the normal 12.1.2 version of x-plane luckily so the world has not ended yet.

**Comment by domrnet** [comment] 2024-11-21 09:45
> I found the same thing with my Ubuntu 24.04 install. I sent the crash reported to LR. I used the readme.pdf in the charts folder and then opened it with the Ubuntu Document and it opened fine.

I've also sent a bug report today. Hopefully more do then Laminar can check it.

**Comment by domrnet** [comment] 2024-11-25 07:43
Laminar asked to raise this with the developer.

**Comment by CrazyKnightGR** [comment] 2024-11-28 16:31
Same here (arch gnome wayland 6.12.1-arch1-1 amdgpu) segmentation fault and the backtrace was:
`(gdb) bt
#0  handle_posix_sig (sig=11, siginfo=0x7fff0ce55f70, context=0x7fff0ce55e40) at ../src/except.c:104
#1  <signal handler called>
#2  0x00007ffd9c003f30 in ?? ()
#3  0x00007fffe1c046c8 in cmsSignalError () from /usr/lib/liblcms2.so.2
#4  0x00007fffe1c06514 in cmsOpenIOhandlerFromMem () from /usr/lib/liblcms2.so.2
#5  0x00007fffe1c0a4fb in cmsOpenProfileFromMemTHR () from /usr/lib/liblcms2.so.2
#6  0x00007fff312ef568 in fz_new_icc_profile () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#7  0x00007fff3126d403 in fz_new_icc_colorspace () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#8  0x00007fff3126d8f3 in fz_new_colorspace_context () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#9  0x00007fff312700c2 in fz_new_context_imp () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#10 0x00007fff3113761e in img::Rasterizer::initFitz() () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#11 0x00007fff311386cc in img::Rasterizer::Rasterizer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#12 0x00007fff31109c20 in maps::DocumentSource::DocumentSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#13 0x00007fff3110c3f5 in maps::LocalFileSource::LocalFileSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<apis::ChartService>) () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#14 0x00007fff3102e60f in avitab::DocumentsApp::loadFile(std::shared_ptr<avitab::DocumentsApp::DocumentPage>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#15 0x00007fff3103112a in avitab::DocumentsApp::createDocumentTab(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#16 0x00007fff31031834 in avitab::DocumentsApp::onSelect(int) () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#17 0x00007fff30fe87b1 in avitab::LVGLToolkit::guiLoop() () from /run/media/Backup/X-Plane 12/Resources/plugins/AviTab/lin_x64/AviTab.xpl
#18 0x00007fffe323ac34 in std::execute_native_thread_routine (__p=0x14553980) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#19 0x00007fffe347f39d in ?? () from /usr/lib/libc.so.6
#20 0x00007fffe350449c in ?? () from /usr/lib/libc.so.6
`

**Comment by fpw** [comment] 2024-11-28 19:27
It seems to be fixed in X-Plane's latest beta according to this thread: https://forums.x-plane.org/index.php?/files/file/44825-avitab-vr-compatible-tablet-with-pdf-viewer-moving-maps-and-more/&page=12&tab=comments#comment-408198

Can you confirm that it's resolved?

**Comment by domrnet** [comment] 2024-11-28 20:45
Yep seems the new update works well with avitab. No issues anymore. LR broke something before as expected ina beta I guess. 
Thanks

**Closed** 2024-11-28 20:54 UTC
