### ISSUE TITLE
cannot find any avitab dataref

### ISSUE THREAD

**Issue by fralbo** [fpw/avitab#135] opened 2022-12-20 18:50 UTC
Hello,
I don't remember if I tested it in XP11 but I cannot find any avitab's dataref in XP12

![This is an image](https://i.imgur.com/MQ8P0Z4.png)

**Comment by fpw** [comment] 2022-12-28 17:25
Hi,

that's a duplicate of #32.
AviTab doesn't send the datarefs to 3rd party tools yet.

**Closed by fpw** 2022-12-28 17:25 UTC
